// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFtiM2Wa2Uqqi60f9Bgmv--QQQCJ9T9ac',
    appId: '1:973082480529:web:cf902264e150b9b6035430',
    messagingSenderId: '973082480529',
    projectId: 'week18-db625',
    authDomain: 'week18-db625.firebaseapp.com',
    storageBucket: 'week18-db625.appspot.com',
    measurementId: 'G-64VKVB4BPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVF69WYvsFWxjJeZTHXhVGRlWtoyU_zVw',
    appId: '1:973082480529:android:e221a9ed9adf45fc035430',
    messagingSenderId: '973082480529',
    projectId: 'week18-db625',
    storageBucket: 'week18-db625.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1QAaRErCX46_N2MdSEYJy4sI69iRshSE',
    appId: '1:973082480529:ios:46ab0c8aa25f2982035430',
    messagingSenderId: '973082480529',
    projectId: 'week18-db625',
    storageBucket: 'week18-db625.appspot.com',
    iosClientId: '973082480529-6n0euumhdon7c6m8r0bqp9549citetcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.week18',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1QAaRErCX46_N2MdSEYJy4sI69iRshSE',
    appId: '1:973082480529:ios:46ab0c8aa25f2982035430',
    messagingSenderId: '973082480529',
    projectId: 'week18-db625',
    storageBucket: 'week18-db625.appspot.com',
    iosClientId: '973082480529-6n0euumhdon7c6m8r0bqp9549citetcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.week18',
  );
}
